/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HazardousSubstanceService } from "../hazardousSubstance.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HazardousSubstanceCreateInput } from "./HazardousSubstanceCreateInput";
import { HazardousSubstance } from "./HazardousSubstance";
import { HazardousSubstanceFindManyArgs } from "./HazardousSubstanceFindManyArgs";
import { HazardousSubstanceWhereUniqueInput } from "./HazardousSubstanceWhereUniqueInput";
import { HazardousSubstanceUpdateInput } from "./HazardousSubstanceUpdateInput";
import { AccidentScenarioFindManyArgs } from "../../accidentScenario/base/AccidentScenarioFindManyArgs";
import { AccidentScenario } from "../../accidentScenario/base/AccidentScenario";
import { AccidentScenarioWhereUniqueInput } from "../../accidentScenario/base/AccidentScenarioWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HazardousSubstanceControllerBase {
  constructor(
    protected readonly service: HazardousSubstanceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HazardousSubstance })
  @nestAccessControl.UseRoles({
    resource: "HazardousSubstance",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHazardousSubstance(
    @common.Body() data: HazardousSubstanceCreateInput
  ): Promise<HazardousSubstance> {
    return await this.service.createHazardousSubstance({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        boilingPoint: true,
        flammabilityLimit: true,
        mass: true,
        typeField: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HazardousSubstance] })
  @ApiNestedQuery(HazardousSubstanceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HazardousSubstance",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hazardousSubstances(
    @common.Req() request: Request
  ): Promise<HazardousSubstance[]> {
    const args = plainToClass(HazardousSubstanceFindManyArgs, request.query);
    return this.service.hazardousSubstances({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        boilingPoint: true,
        flammabilityLimit: true,
        mass: true,
        typeField: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HazardousSubstance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HazardousSubstance",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hazardousSubstance(
    @common.Param() params: HazardousSubstanceWhereUniqueInput
  ): Promise<HazardousSubstance | null> {
    const result = await this.service.hazardousSubstance({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        boilingPoint: true,
        flammabilityLimit: true,
        mass: true,
        typeField: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HazardousSubstance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HazardousSubstance",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHazardousSubstance(
    @common.Param() params: HazardousSubstanceWhereUniqueInput,
    @common.Body() data: HazardousSubstanceUpdateInput
  ): Promise<HazardousSubstance | null> {
    try {
      return await this.service.updateHazardousSubstance({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          boilingPoint: true,
          flammabilityLimit: true,
          mass: true,
          typeField: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HazardousSubstance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HazardousSubstance",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHazardousSubstance(
    @common.Param() params: HazardousSubstanceWhereUniqueInput
  ): Promise<HazardousSubstance | null> {
    try {
      return await this.service.deleteHazardousSubstance({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          boilingPoint: true,
          flammabilityLimit: true,
          mass: true,
          typeField: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/accidentScenarios")
  @ApiNestedQuery(AccidentScenarioFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AccidentScenario",
    action: "read",
    possession: "any",
  })
  async findAccidentScenarios(
    @common.Req() request: Request,
    @common.Param() params: HazardousSubstanceWhereUniqueInput
  ): Promise<AccidentScenario[]> {
    const query = plainToClass(AccidentScenarioFindManyArgs, request.query);
    const results = await this.service.findAccidentScenarios(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        thermalRadiationIntensity: true,
        probabilityDamage: true,

        pipeline: {
          select: {
            id: true,
          },
        },

        hazardousSubstance: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/accidentScenarios")
  @nestAccessControl.UseRoles({
    resource: "HazardousSubstance",
    action: "update",
    possession: "any",
  })
  async connectAccidentScenarios(
    @common.Param() params: HazardousSubstanceWhereUniqueInput,
    @common.Body() body: AccidentScenarioWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accidentScenarios: {
        connect: body,
      },
    };
    await this.service.updateHazardousSubstance({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/accidentScenarios")
  @nestAccessControl.UseRoles({
    resource: "HazardousSubstance",
    action: "update",
    possession: "any",
  })
  async updateAccidentScenarios(
    @common.Param() params: HazardousSubstanceWhereUniqueInput,
    @common.Body() body: AccidentScenarioWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accidentScenarios: {
        set: body,
      },
    };
    await this.service.updateHazardousSubstance({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/accidentScenarios")
  @nestAccessControl.UseRoles({
    resource: "HazardousSubstance",
    action: "update",
    possession: "any",
  })
  async disconnectAccidentScenarios(
    @common.Param() params: HazardousSubstanceWhereUniqueInput,
    @common.Body() body: AccidentScenarioWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accidentScenarios: {
        disconnect: body,
      },
    };
    await this.service.updateHazardousSubstance({
      where: params,
      data,
      select: { id: true },
    });
  }
}
