/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Pipeline } from "./Pipeline";
import { PipelineCountArgs } from "./PipelineCountArgs";
import { PipelineFindManyArgs } from "./PipelineFindManyArgs";
import { PipelineFindUniqueArgs } from "./PipelineFindUniqueArgs";
import { CreatePipelineArgs } from "./CreatePipelineArgs";
import { UpdatePipelineArgs } from "./UpdatePipelineArgs";
import { DeletePipelineArgs } from "./DeletePipelineArgs";
import { AccidentScenarioFindManyArgs } from "../../accidentScenario/base/AccidentScenarioFindManyArgs";
import { AccidentScenario } from "../../accidentScenario/base/AccidentScenario";
import { PipelineService } from "../pipeline.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Pipeline)
export class PipelineResolverBase {
  constructor(
    protected readonly service: PipelineService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Pipeline",
    action: "read",
    possession: "any",
  })
  async _pipelinesMeta(
    @graphql.Args() args: PipelineCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Pipeline])
  @nestAccessControl.UseRoles({
    resource: "Pipeline",
    action: "read",
    possession: "any",
  })
  async pipelines(
    @graphql.Args() args: PipelineFindManyArgs
  ): Promise<Pipeline[]> {
    return this.service.pipelines(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Pipeline, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Pipeline",
    action: "read",
    possession: "own",
  })
  async pipeline(
    @graphql.Args() args: PipelineFindUniqueArgs
  ): Promise<Pipeline | null> {
    const result = await this.service.pipeline(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Pipeline)
  @nestAccessControl.UseRoles({
    resource: "Pipeline",
    action: "create",
    possession: "any",
  })
  async createPipeline(
    @graphql.Args() args: CreatePipelineArgs
  ): Promise<Pipeline> {
    return await this.service.createPipeline({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Pipeline)
  @nestAccessControl.UseRoles({
    resource: "Pipeline",
    action: "update",
    possession: "any",
  })
  async updatePipeline(
    @graphql.Args() args: UpdatePipelineArgs
  ): Promise<Pipeline | null> {
    try {
      return await this.service.updatePipeline({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Pipeline)
  @nestAccessControl.UseRoles({
    resource: "Pipeline",
    action: "delete",
    possession: "any",
  })
  async deletePipeline(
    @graphql.Args() args: DeletePipelineArgs
  ): Promise<Pipeline | null> {
    try {
      return await this.service.deletePipeline(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [AccidentScenario], { name: "accidentScenarios" })
  @nestAccessControl.UseRoles({
    resource: "AccidentScenario",
    action: "read",
    possession: "any",
  })
  async findAccidentScenarios(
    @graphql.Parent() parent: Pipeline,
    @graphql.Args() args: AccidentScenarioFindManyArgs
  ): Promise<AccidentScenario[]> {
    const results = await this.service.findAccidentScenarios(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
